Ignore doc_markdown clippy false positive
Clippy bug: https://github.com/rust-lang/rust-clippy/issues/7421

    error: backticks are unbalanced
       --> src/lib.rs:128:1
        |
    128 | / //!   Any error type that implements `std::error::Error` or dereferences to `dyn
    129 | | //!   std::error::Error` will work as a source.
    130 | | //!
    131 | | //!   ```rust
    132 | | //!   # use std::fmt::{self, Display};
        | |______________________________________^
        |
        = note: `-D clippy::doc-markdown` implied by `-D clippy::pedantic`
        = help: a backtick may be missing a pair
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown