Add regression test for issue 335
    error[E0277]: `PathBuf` doesn't implement `std::fmt::Display`
       --> tests/test_expr.rs:105:14
        |
    104 |     #[derive(Error, Debug)]
        |              ----- in this derive macro expansion
    105 |     #[error("{A} {b}", b = &0 as &dyn Trait<i32, A = i32>)]
        |              ^^^ `PathBuf` cannot be formatted with the default formatter; call `.display()` on it
        |
        = help: the trait `std::fmt::Display` is not implemented for `PathBuf`
        = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
        = note: call `.display()` or `.to_string_lossy()` to safely print paths, as they may contain non-Unicode data
        = note: this error originates in the macro `$crate::format_args` which comes from the expansion of the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)