Add failing regression test for issue 86
    error[E0425]: cannot find value `_0` in this scope
       --> tests/test_display.rs:208:29
        |
    208 |             #[derive(Debug, Error)]
        |                             ^^^^^ not found in this scope