Add test of dynamically sized error type
    error[E0599]: the method `as_display` exists for reference `&str`, but its trait bounds were not satisfied
      --> tests/test_path.rs:26:9
       |
    26 | #[error("{tail}")]
       |         ^^^^^^^^ method cannot be called on `&str` due to unsatisfied trait bounds
       |
       = note: the following trait bounds were not satisfied:
               `str: Sized`
               which is required by `&str: AsDisplay<'_>`